FROM php:8-apache

# Basic system software
RUN apt-get update && \
  apt-get install -y --no-install-recommends git zip unzip libgmp-dev curl libzip-dev libonig-dev libpng-dev libjpeg-dev libjpeg62-turbo-dev libxml2-dev && \
  pecl channel-update pecl.php.net && \
  pecl install apcu igbinary && \
  pecl bundle redis && cd redis && phpize && ./configure --enable-redis-igbinary && make && make install && \
  docker-php-ext-enable apcu igbinary opcache redis && \
  docker-php-source delete

# Composer
RUN curl --silent --show-error https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

# Enable apache modules
RUN a2enmod proxy && \
  a2enmod proxy_http && \
  a2enmod proxy_ajp && \
  a2enmod rewrite && \
  a2enmod deflate && \
  a2enmod headers && \
  a2enmod proxy_balancer && \
  a2enmod proxy_connect && \
  a2enmod ssl && \
  a2enmod cache && \
  a2enmod expires

# GD
RUN docker-php-ext-configure gd --with-jpeg

# Install remaining php modules
RUN docker-php-ext-install gmp mbstring pdo zip intl mysqli pdo pdo_mysql sockets gd soap xml dom

# Install imagick
RUN apt-get update && apt-get install -y libmagickwand-dev --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/src/php/ext/imagick; \
  curl -fsSL https://github.com/Imagick/imagick/archive/06116aa24b76edaf6b1693198f79e6c295eda8a9.tar.gz | tar xvz -C "/usr/src/php/ext/imagick" --strip 1; \
  docker-php-ext-install imagick;

# PHP configs for Apache
RUN echo "memory_limit = 1024M" > /usr/local/etc/php/conf.d/rms-php.ini
RUN echo "date.timezone = Europe/Zurich" >> /usr/local/etc/php/conf.d/rms-php.ini

WORKDIR /var/www/html
